### ISSUE TITLE
taxableIncome has deductibleExpenses subtracted 

### ISSUE THREAD

**Issue by eduardhojbota** [taxepfa/taxepfa.github.io#35]
https://github.com/taxepfa/taxepfa.github.io/blob/d389c6f6400033f1b58641b8f08773ee4a3a8b87/lib/taxes.ts#L71C79-L71C97

income already has deductibleExpenses subtracted but when calculating taxableIncome it is subtracted again

**Comment by icflorescu** [comment]
Fixed, thanks.
